### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by MightyCupcakes** [CS2103AUG2016-F10-C2/main#156]
- [x] Update user guide and developer guide to reflect the new changes in behaviours on the program made in v0.4

- [x] Update the about.us to be the same format as the picture below
![image](https://cloud.githubusercontent.com/assets/19278361/19736291/414d5d2c-9be1-11e6-8688-ac2b61e873fd.png)

**Comment by tanboonjoon** [comment]
updated developerGuide to explain some reasons behind our implementation

**Comment by tanboonjoon** [comment]
references #130 
@ningyuuu  @ericsssan  , please pick 1 or 2 product and survey in details thx
- [ ] Todoist
- [ ] Ominifocus
- [ ] google keep

**Comment by ningyuuu** [comment]
i'll do google keep and todoist

**Comment by tanboonjoon** [comment]
updated ReadMe to give credit for external library

**Comment by tanboonjoon** [comment]
@MightyCupcakes @ningyuuu @ericsssan , try to update the about.us individually. i dont think we can remember in details what the rest of the teammates has done. So should OTOT update our own one.
