### ISSUE TITLE
Thursday discussion regarding friday demo

### ISSUE THREAD

**Issue by tanboonjoon** [CS2103AUG2016-F10-C2/main#178]
@MightyCupcakes @ningyuuu @ericsssan 
Apparently it not just changes we have to made. The Friday demo should cover **all features** including one that we have go thru away. The Handbook suggest it to be done by 2 people. and the next 2 will be doing next week.  I suggest we should do as a team for both week to get a 'feel' of the whole demo.

Agenda 

- A well-prepared savefile ( at least 50 item, range from 2 week ago to 2 week later ) 
- A well-prepared command ( so you can just copy and paste instead of typing on the spot)
- The whole flow of the demo. 
 1.  Order of which command should be covered
 2. Order of which we should take turn speaking ( directly related to above )

Anything that is missed out can be suggest here or whatapps 
Usual skype/hangouts time at 9pm all ok?

**Comment by tanboonjoon** [comment]
V0.4 demo : copy from CS2103 handbook
It should be a 'well prepared' demo. You should know in advance exactly what you'll do in the demo.
It should be a full demo: Cover all features you have, not just features you added recently.
It is a 'sitting down' demo: As before, you'll be demonstrating the features using the TV while sitting down.
Tutor will not interrupt you during the demo. That means you should finish within the given time.
It should be done by 2 members (i.e. one person do the first half, the other do the 2nd half).
If you are not taking part in this demo, you must take part in V0.5 demo.
One or more persons can do the typing for the whole demo. Speaking should be done by the two designated to do the demo.
The app should be populated with a significant amount of realistic data at the start. e.g data going back to at least two weeks and up to two weeks in future, about 50 items in total.
Grading: Similar to V0.3

**Comment by ningyuuu** [comment]
ok, 9pm is good.
