### ISSUE TITLE
Freetime command tests failing for some reason

### ISSUE THREAD

**Issue by MightyCupcakes** [CS2103AUG2016-F10-C2/main#198]
Two tests that seemed to fail suddenly (probably due to dates again):

guitests.FreetimeTest > validCommandLongEventWithManyEvent FAILED
    org.junit.ComparisonFailure: expected:<on 31/10/2016: [There is a ongoing event from 30/10/2016 1430 to 01/11/2016 1430  ]> but was: on 31/10/2016: [you have 0 freeslots]

guitests.FreetimeTest > validCommandOneOngoingEvent FAILED
    org.junit.ComparisonFailure: expected:<[on 31/10/2016: There is a ongoing event from 30/10/2016 1430 to 01/11/2016 1430 
    ]> but was:<[You are free for the day, trying clearing some reminders.]>

**Comment by tanboonjoon** [comment]
The problem is with a slight bug found in findCommand,
disabled the test case until i fix it
