### ISSUE TITLE
Things to complete for V0.5 submission

### ISSUE THREAD

**Issue by MightyCupcakes** [CS2103AUG2016-F10-C2/main#231]
- [x] Create a xml file with sample data at \src\test\data\ManualTesting\SampleData.xml
File should contain at least 50+ entries

- [x] Create a .md file outlining the steps to test the program at src\test\data\ManualTesting\TestScript.md
The test should contain expected results (screenshots not needed) and the whole test should not exceed 20 minutes. The test should cover all functionality of the app.

- [x] Submit source code by tagging v0.5 on github. Make sure all collated codes are up to date because they cannot be updated after the deadline

- [x]  Upload the fat jar file to IVLE. File name: [team][project name].jar e.g. [T09-C1][ToDoo Pro].jar 

- [x] Update documentation on Github.

- [x] Copy and paste contents of documentation into a .docx file following the format.
[[TeamID][ProjectName].docx](https://github.com/CS2103AUG2016-F10-C2/main/files/573190/TeamID.ProjectName.docx)

- [x] Convert the said .docx into pdf with name [TEAM_ID][Project Name].pdf e.g. [T09-C1][ToDoo Pro].pdf and upload it to IVLE

**Comment by tanboonjoon** [comment]
https://github.com/CS2103AUG2016-F10-C2/main/blob/testScript/src/test/data/ManualTesting/forDemoUse.xml
about 95 entries

**Comment by MightyCupcakes** [comment]
References #211
