### ISSUE TITLE
FlexiCommands

### ISSUE THREAD

**Issue by ericsssan** [CS2103AUG2016-F10-C2/main#53]
FlexiCommands: High flexibility in command format. e.g., non-strict ordering of keywords, ability to specify aliases for commands, support for more ‘natural’ language input, multiple undo/redo, How flexible should the format be? As flexible, intuitive, and user-friendly as you can make it.

- [X] Non-strict ordering of argument such as description, start date, end date and tag. Done by @MightyCupcakes #31 
- [x] Ability to specify aliases for commands. 
- [ ] support for more 'natural' language input. ( maybe not doing )

**Comment by MightyCupcakes** [comment]
NLP commands are classified as a nice to have and hence shall be suspended till someone decides to pick it up.
