### ISSUE TITLE
GoodGui

### ISSUE THREAD

**Issue by ericsssan** [CS2103AUG2016-F10-C2/main#54]
A good GUI to give visual feedback to the user e.g., 
- [ ] in-built guidance for new users, 
- [ ] good visual feedback for actions, feedback while typing commands, 
- [ ] hotkey to activate/hide, notifications, etc. 
- [ ] Agenda Window? http://jfxtras.org/ (quite impossible)
- [x] Add in feedback when a new task is added

**Comment by tanboonjoon** [comment]
@ericsssan are u doing this? if not pls close this
